-- Suggested measures for the FraSoHome semantic model.
-- Table names can be adjusted to the names generated by your Fabric semantic model.

Ventas netas =
CALCULATE(
    SUM(gold_fact_transacciones[importe_abs]),
    gold_fact_transacciones[tipo_movimiento] = "VENTA"
)

Importe devoluciones =
CALCULATE(
    SUM(gold_fact_transacciones[importe_abs]),
    gold_fact_transacciones[tipo_movimiento] = "DEVOLUCION"
)

Tasa devolución =
DIVIDE(
    [Importe devoluciones],
    [Ventas netas]
)

Margen bruto =
CALCULATE(
    SUM(gold_fact_transacciones[margen_bruto]),
    gold_fact_transacciones[tipo_movimiento] = "VENTA"
)

Margen % =
DIVIDE(
    [Margen bruto],
    [Ventas netas]
)

Clientes en riesgo =
CALCULATE(
    DISTINCTCOUNT(gold_cliente_score[customer_id]),
    gold_cliente_score[riesgo_fuga] = TRUE()
)

Ticket medio =
DIVIDE(
    [Ventas netas],
    CALCULATE(
        DISTINCTCOUNT(gold_fact_transacciones[doc_id]),
        gold_fact_transacciones[tipo_movimiento] = "VENTA"
    )
)

Unidades vendidas =
CALCULATE(
    SUM(gold_fact_transacciones[cantidad_abs]),
    gold_fact_transacciones[tipo_movimiento] = "VENTA"
)

